name: $(BuildDefinitionName).$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- ci

variables:
  buildConfiguration: 'Release'
  publishRootPath: '\\files\Production\DBOrchestrator'
  environmentName: 'CI'

stages:
- template: BuildStage.yml
  parameters:
    buildConfiguration: '$(buildConfiguration)'

- template: TestStage.yml
  parameters:
    buildConfiguration: '$(buildConfiguration)'

- template: DeployStage.yml
  parameters:
    buildConfiguration: '$(buildConfiguration)'