name: $(BuildDefinitionName).$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- ci

variables:
  buildConfiguration: 'release'
  runtimeIdentifier: 'win-x64'
  publishRootPath: '\\files\Production\DBOrchestrator'

stages:
#- template: BuildStage.yml
#  parameters:
#   buildConfiguration: '$(buildConfiguration)'
#    runtimeIdentifier: '$(runtimeIdentifier)'

#- template: TestStage.yml
#  parameters:
#    buildConfiguration: '$(buildConfiguration)'

- template: DeployStage.yml
  parameters:
    buildConfiguration: '$(buildConfiguration)'
    runtimeIdentifier: '$(runtimeIdentifier)'
    publishRootPath: '$(publishRootPath)'