name: $(BuildDefinitionName).$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- ci

variables:
  buildConfiguration: 'release'
  runtimeIdentifier: 'win-x64'
  publishRootPath: '\\files\Production\DBOrchestrator'

stages:
- template: DeployStage.yml
  parameters:
    buildConfiguration: '$(buildConfiguration)'
    runtimeIdentifier: '$(runtimeIdentifier)'
    publishRootPath: '$(publishRootPath)'
