name: $(BuildDefinitionName).$(Date:yyyyMMdd)$(Rev:.r)

resources:
  repositories:
  - repository: 'PowerShellScripts'
    type: git
    name: Home/BessemerMgmt.PowerShellScripts

trigger:
- master

variables:
  buildConfiguration: 'Release'
  publishRootPath: '\\files\Production\BessemerMgmt.DbOrchestrator'

stages:
- template: BuildStage.yml
  parameters:
    buildConfiguration: '$(buildConfiguration)'

- template: TestStage.yml
  parameters:
    buildConfiguration: '$(buildConfiguration)'

- template: DeployStage.yml
  parameters:
    buildConfiguration: '$(buildConfiguration)'
    publishRootPath: '$(publishRootPath)'