parameters:
  dotNetCoreSDKVersion: '3.1.101'
  buildConfiguration: ''

stages:
 - stage: 'Test'
   displayName: 'Run Unit Tests'
   dependsOn: []
   jobs:
   - job: 'Test'
     displayName: 'Run Unit Tests'
     pool: Default
     workspace:
      clean: all
     steps:
     - task: UseDotNet@2
       displayName: 'Download DotNet Core SDK ${{parameters.dotNetCoreSDKVersion}}'
       inputs:
        packageType: sdk
        version: '${{parameters.dotNetCoreSDKVersion}}'
     - task: DotNetCoreCLI@2
       displayName: 'Restore Packages'
       inputs:
        command: restore
        feedsToUse: config
        nugetConfigPath: nuget.config
     - task: DotNetCoreCLI@2
       displayName: 'Run Tests (${{parameters.buildConfiguration}})'
       inputs:
         command: test
         projects: '**/*Tests/*.csproj'
         arguments: '--configuration ${{parameters.buildConfiguration}} --settings "$(System.DefaultWorkingDirectory)\CodeCoverage.runsettings" --collect "Code Coverage"'
